on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_PRODUCT_SERVER_URL: ${{ secrets.REACT_APP_PRODUCT_SERVER_URL }}
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: buxianshan/fine-sftp-deployer@v0.1.5
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ secrets.FTP_HOST }}
        port: 22
        ssh_private_key: ${{ secrets.FTP_PASSWORD }}
        local_path: ./build/
        # dist file path on your server
        remote_path: ${{ secrets.FTP_REMOTE_FOLDER }}
        clear_remote_path: true
