on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_PRODUCT_SERVER_URL: ${{ secrets.REACT_APP_PRODUCT_SERVER_URL }}
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: sand4rt/ftp-deployer@v1.4
      with:
        sftp: true
        host: ${{ secrets.FTP_HOST }}
        port: 22
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }}
        local_folder: build
        cleanup: true
        include: '["*", "**/*", ".*"]'
        exclude: '[]'
        pasive: true
